### Site Settings ###
title               : tnya
description         : >-
                      "
                      I create visuals;
                      that each narrate a story through a play of form, colour and texture
                      "
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : tanayarr/tnya.github.io # Change to <your-username>/<your-username>.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Tanaya Rao Raj
  image             : ./images/logo/tnya.png
# behance           : your_username
# dribbble          : your_username
  email             : tanayarr@gmail.com
# facebook          : your_username
  instagram         : tanayarraj
  linkedin          : tanaya-raj-00a157160
# medium            : your_username
  vimeo             : user97150370
  youtube           : UC1whWbAoNmqBKGrgRAUaLdQ


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
